### ISSUE TITLE
Error when using CHP-py with jupyterhb

### ISSUE THREAD

**Issue by AbdealiLoKo** [corridor/configurable-http-proxy#16]
I'm using this py CHP with my jupyterhub as an alternative to nodejs CHP 
So, whenever, I try to open a notebook, I'm seeing the below exception in proxy logs, which is not the case for the other CHP. As a result, the notebook keeps loading 

```
`Traceback (most recent call last):
  File "/export/apps/python/3.10/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/export/apps/python/3.10/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/export/apps/python/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 530, in write
    self._check_closed()
  File "/export/apps/python/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 1019, in _check_closed
    raise StreamClosedError(real_error=self.error)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/apps/python/3.10/lib/python3.10/site-packages/tornado/websocket.py", line 635, in _run_callback
    result = callback(*args, **kwargs)
  File "/export/apps/python/3.10/lib/python3.10/site-packages/configurable_http_proxy/handlers.py", line 414, in on_message
    self.ws_client.write_message(message)
  File "/export/apps/python/3.10/lib/python3.10/site-packages/tornado/websocket.py", line 1500, in write_message
    return self.protocol.write_message(message, binary=binary)
  File "/export/apps/python/3.10/lib/python3.10/site-packages/tornado/websocket.py", line 1088, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError`
```

_Originally posted by @SMHari in https://github.com/corridor/configurable-http-proxy/issues/11#issuecomment-1403732807_

**Comment by AbdealiLoKo** [comment]
Hi @SMHari can you provide the steps to reproduce this ?
 - Which version of python, jupyterhub, notebook, etc. Which OS
 - Are you using jupyterlab or notebook ?
 - What configurations are you using in jupyterhub

I am currently using this project for a bunch of projects and it seems to work well.

**Comment by SMHari** [comment]
Hey @AbdealiLoKo 
Sure
1. Using python 3.10, OSS JupyterHub is 3.1.0
2. The setup I'm using is from z2jh in k8s (https://z2jh.jupyter.org/en/stable/)
3. using custom authenticators and spawners, but I hope that shouldn't be the issue

**Comment by SMHari** [comment]
@AbdealiLoKo you mean the notebook is loading fine and can execute the contents in the cell?

also would like to understand, what's the purpose of this two configparams.
1. c.ConfigurableHTTPProxy.command
2. c.Spawner.cmd

I'm using a custom implementation of Spawner,  a wrapper over KubeSpawner. 

ConfigurableHTTPProxy.command - I don't see this option in the OSS doc. I just use the options mentioned in the wiki [here](https://jupyterhub.readthedocs.io/en/stable/reference/separate-proxy.html) running proxy separately from the hub

**Comment by AbdealiLoKo** [comment]
Yes, I am able to login with my user account, create a folder, create a notebook, run python commands in that notebook

Both of the configurations I mentioned are JupyterHub configurations:
 - `c.ConfigurableHTTPProxy.command` [link](https://jupyterhub.readthedocs.io/en/stable/api/proxy.html#jupyterhub.proxy.ConfigurableHTTPProxy.command) - The eecutable path to use for `configurable-http-proxy`
 - `c.Spawner.cmd` [link](https://jupyterhub.readthedocs.io/en/stable/api/spawner.html#jupyterhub.spawner.Spawner.cmd) - The executable path to use for the `jupyterhub-singleuser`

The default values just take it from the existing `PATH`:
```py
c.ConfigurableHTTPProxy.command = 'configurable-http-proxy'
c.Spawner.cmd = 'jupyterhub-singleuser'
```

I just gave them explicitly to ensure it is being taken from my virtualenv (I have a lot of jupyters andd configurable-http-proxy installed locally with varying versinos and prefer not to muck around with my PATH)
Using separate proxy is fine too

I think it would be helpful to narrow down the problem.
So, would it be possible for you to run the same steps I mentioned above to ensure it is not an issue with your Python, OS, etc. ?
An then maybe create a minimum reproducible example to see if it is some specific issue with KubeSpawner or something else ?

**Comment by AbdealiLoKo** [comment]
I tried to go towards your setup with:
```py
$ cat jupyterhub_config.py
import os, sys
c.ConfigurableHTTPProxy.should_start = False
c.ConfigurableHTTPProxy.auth_token = 'abc'
c.Spawner.cmd = [os.path.join(sys.prefix, 'bin', 'jupyterhub-singleuser')]
```
And ran the following separately:
```sh
$ CONFIGPROXY_AUTH_TOKEN=abc venvtest/bin/configurable-http-proxy
```

And that seems to work fine (i.e. able to login, create a notebook, run python) too

I am not very experienced with Kubernetes, and looked like it would be complex for me to setup quickly

**Comment by VitaliyFedorov** [comment]
I have absolutly the same issue, but it's appear only when I trying to start VS Code via jupyterhub-vscode-proxy.
If I install CHP-nodejs all works fine (notebook, terminal, python, VS Code), but if CHP-py installed all fine except VS Code (jupyterhub-vscode-proxy).
May be somebody has any ideas to how to fix this or how I can investigate it.

configurable-http-proxy 0.2.3
jupyterhub 2.3.1
jupyter-vscode-proxy 0.2
jupyterlab 3.5.3
jupyter-server-proxy 3.2.2

jupyterhub published to on prem k8s cluster

`
c.ConfigurableHTTPProxy.should_start = False
c.ConfigurableHTTPProxy.auth_token = '<some_value_from_env_var_CONFIGPROXY_AUTH_TOKEN>'
`
CONFIGPROXY_AUTH_TOKEN env var passed to proxy container

**Comment by SMHari** [comment]
➕ 
@AbdealiLoKo 
I'm running the entire stack in k8s and seem to get my single-user pod up and running without issues.
But while opening any notebook, I'm facing the issue 

Need to backtrack the stack trace to understand whether those scenarios are missing any required handling

**Comment by AbdealiLoKo** [comment]
@VitaliyFedorov thanks for the feedback. I have not seen jupyter-vscode-proxy before - I can take a look at it tomorrow to understand what could be the issue.

Meanwhile if you're able to provide a minimum reproducible example with jupyter-vscode-proxy which can reproduce your error - that would be very helpful

**Comment by AbdealiLoKo** [comment]
So, @VitaliyFedorov I took a quick look at jupyter-vscode-proxy [pypi link](https://pypi.org/project/jupyter-vscode-proxy/)
But I could see no documentation of what it does nor how can I set it up locally to reproduce the issue you reported

I have asked a question on the repo: https://github.com/betatim/vscode-binder/issues/37
But it would be great if you can give me a reproducible example

**Comment by VitaliyFedorov** [comment]
code-server has to be installed on jupyterlab and also following py packages: jupyter-server-proxy and jupyter-vscode-proxy. After that in jupyterlab should appear button with title "VS Code". When you press it a new tab will be open with web version of VS Code
